# This is a GoReleaser configuration for a Terraform provider.
# Visit https://goreleaser.com for documentation on how to customize this file.

version: 2

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'

signs:
  - cmd: gpg
    artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "F57F85FC7975F22BBC3F25049C173EB1B531AA1F"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^Merge pull request'
      - '^Merge remote-tracking branch'
      - '^Merge branch'

# Publisher for Terraform registry
publishers:
  - name: terraform-registry
    ids:
      - default
    dir: '{{ dir .ArtifactPath }}'
    cmd: |
      gpg --batch --detach-sign --local-user F57F85FC7975F22BBC3F25049C173EB1B531AA1F --output {{ .ArtifactName }}_SHA256SUMS.sig {{ .ArtifactName }}_SHA256SUMS
